Rules = [
"""  """,
"""  """,
""" Le principe est simple : """,
""" * Les loups-garous doivent tuer ceux qui n'en sont pas. """,
""" * Ceux qui ne sont pas des loups-garous doivent les tuer. """,
"""  """,
""" Le déroulement d'une partie : """,
"""     Une partie se déroule sur plusieurs "jours". En effet, la nuit, les loups-garous assassinent un villageois alors que le jour,les villageois se concertent afin de découvrir l'identité des loups-garous. """,
"""  """,
""" Les personnages : """,
"""     Les loups Garous : """,
"""         Chaque nuit, ils dévorent un villageois. Le jour, ils tentent de masquer leur identité afin que les villageois ne découvrent pas qui ils sont. """,
"""  """,
"""     Les villageois (ceux qui ne sont pas loup-garou) : """,
"""         Chaque nuit, l'un d'entre eux est dévoré par les loups-garous et est éliminé. Le lendemain, ils se concertent afin de trouver des signes trahissant l'identité d'un coupable. Ils décident ensuite de la personne qui sera executée. """,
"""  """,
""" Les différents villageois : """,
"""     Le simple villageois : """,
"""         Il n'a aucune compétence particulière. Ses seules armes sont la capacité d'analyse des comportements pour identifier les Loups Garous et la force de conviction pour empêcher l'exécution de l'innocent qu'il est. """,
"""  """,
"""     La voyante : """,
"""         Chaque nuit, elle découvre la vraie personnalité d'un joueur de son choix. Elle doit aider les autres villageois, mais rester discrète pour ne pas être démasquée par les Loups-garous. """,
"""  """,
"""     Le chasseur : """,
"""         S'il se fait dévorer par les Loups Garous ou exécuter malencontreusement par les joueurs, le Chasseur a le pouvoir de répliquer avant de rendre l'âme, en éliminant immédiatement n'importe quel autre joueur de son choix. """,
"""  """,
"""     Cupidon : """,
"""         En décochant ses célèbres flèches magiques, Cupidon a le pouvoir de rendre 2 personnes amoureuses à jamais. La première nuit, il désigne 2 joueurs comme étant amoureux. Si l'un des amoureux est éliminé, l'autre meurt de chagrin immédiatement. Un Amoureux ne doit jamais voter contre son bien-aimé. """,
"""         Attention: Si l'un des deux Amoureux est un Loup-Garou et l'autre un Villageois, le but de la partie change pour eux. Pour vivre en paix leur amour et gagner la partie, ils doivent éliminer tous les autres joueurs , Loups-Garous et Villageois, en respectant les règles du jeu. """,
"""  """,
"""     La sorcière : """,
"""         Elle sait concocter 2 potions extrèmement puissantes: Une potion de guérison, pour ressusciter le joueur tué par les Loups-Garous, une potion d'empoisonnement, utilisée la nuit pour éliminer un joueur.""",
"""         La sorcière ne peut utiliser chaque potion qu'une seule fois dans la partie. Elle peut se servir de ses 2 potions dans la même nuit. Le matin suivant il pourra, suivant l'usage de ce pouvoir, y avoir 0 mort, 1 mort ou 2 morts. La sorcière peut utiliser les potions à son profit, et donc se guérir elle-même. """,
"""  """,
"""     La Petite Fille : """,
"""         La Petite Fille peut, en entrouvrant les yeux, espionner les Loups Garous pendant leur réveil. Si elle se fait surprendre par un des Loups-Garous, elle meurt immédiatement (en silence), à la place de la victime désignée. La Petite Fille ne peut espionner que la nuit, durant le tour d'éveil des Loups-Garous. """,
"""  """,
"""     Le voleur : """,
"""         Après disttribution, les deux cartes non distribuées sont placées au centre de la table face cachée. La première nuit, le voleur pourra prendre connaissance de ces deux cartes, et échanger sa carte contre l'une des deux autres. Si ces deux cartes sont des Loups Garous, il est obligé d'échanger sa carte contre un des deux Loups Garous. Il jouera alors ce personnage jusqu'à la fin de la partie. """,
"""  """,
"""     Le maire : """,
"""         Son rôle est primordial parmi les villageois. En effet, son vote vaut 5. Cependant, s'il meurt, tout le village à part la sorcière MEURT.""",
"""  """,
]


Cycle = ["La nuit tombe sur le village...", "Le jour se lève sur le village...", "Les joueurs votent..."]
